name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 3 */2 * *'  # Every 2 days at 3 AM UTC

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    
    steps:
      - name: Call Supabase API
        run: |
          curl -X GET "$SUPABASE_URL/rest/v1/registrations?limit=1" \
          -H "apikey: $SUPABASE_KEY" \
          -H "Content-Type: application/json" 